version: "3"
services:
  web:
    image: lastcoolnameleft/python-helloworld
    deploy:
      replicas: 3 # to start, set this to 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:

